services:
  mimicached:
    build: ../../../../Dockerfile/mimicached-iip-af_xdp
    image: jumpstart-mimicached-iip-af_xdp:latest
    cap_add:
      - SYS_NICE
      - SYS_ADMIN
      - NET_ADMIN
      - IPC_LOCK
      - BPF
    command: sh -c "/mimicached/a.out -l 0 -i eth0 -- -p 11211 -m 1024 -z 100000"
  memtier_benchmark:
    build:
      context: .
      dockerfile_inline: |
        FROM redislabs/memtier_benchmark:2.2.0
        RUN apt update; apt install -y ethtool
    depends_on:
      - mimicached
    cap_add:
      - NET_ADMIN
    entrypoint: sh -c "ethtool -K eth0 rx off; memtier_benchmark -h mimicached -p 11211 -P memcache_text -t 3 -c 64 --key-maximum 1 --ratio=0:1 --test-time=10"
